### ISSUE TITLE
geojsonServiceAddress from database

### ISSUE THREAD

**Issue by mibalas** [utahemre/Leaflet.GeoJSONAutocomplete#1]
Hi, I saved a layer in mysql and I'm showing in the map as a geojson.

How can I put this geojson in the geojsonServiceAddress option?

And

How can I indicate which field it will search?

**Comment by utahemre** [comment]
Hi there,

This plugin runs with rest web services. You need to have rest web service that takes minimum 2 parameters (search and limit) and you can use search parameter for searching.

No matter which database you are using and how you organize your code that query your database. You can use search parameter in any part of your query.
