### ISSUE TITLE
JSON NOT WORKING AT ALL

### ISSUE THREAD

**Issue by umsdavid** [utahemre/Leaflet.GeoJSONAutocomplete#2]
Hi,

I have try to use the geojson search. The search autocomplete listed all the files in the json without searching on it and the limit also not working. I'm not sure if you notice this, try with your demo, try search for one name, it will always show all name even if you search the correct name it will always display all records from the json. so its not working.

**Comment by utahemre** [comment]
Hello,

This json file is just an example result. If you want to use this plugin you must have a restful service that returns geojson. All the parameters are for restful services, not .json files.
