### ISSUE TITLE
Make styling from css more unique

### ISSUE THREAD

**Issue by Netkaart-feedback** [utahemre/Leaflet.GeoJSONAutocomplete#3]
The css styling classes at the moment have very generic names:
for instance:
.divider
.result
.list
.content
etc
To avoid confusion with other plugins or styling, class names should be more specific:
.autocomplete-divider
.autocomplete-result
.autocomplete-list
.autocomplete-content
etc.

File attached fixes this issue:
[geojsonautocomplete-issue3.zip](https://github.com/utahemre/Leaflet.GeoJSONAutocomplete/files/4002769/geojsonautocomplete-issue3.zip)

**Comment by utahemre** [comment]
thanks for contribution
